ruby/rails/p2plearning/config/routes.rb
P2plearning::Application.routes.draw do
  get "profiles/me"

  resources :profiles

  devise_for :users

  resources :courses

  get "info/intro"

  get "info/terms"

  get "info/privacy"

  get "info/about"

  root :to => "info#intro"

end

ruby/rails/p2plearning/app/models/course.rb
class Course < ActiveRecord::Base
  # def initialize()
  #   @created = Time.now
  #   @updated = Time.now
  # end
end

ruby/rails/p2plearning/app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

ruby/rails/p2plearning/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

ruby/rails/p2plearning/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

ruby/rails/p2plearning/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.xml
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.xml
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.xml
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.xml
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to(@course, :notice => 'Course was successfully created.') }
        format.xml  { render :xml => @course, :status => :created, :location => @course }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.xml
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to(@course, :notice => 'Course was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.xml
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to(courses_url) }
      format.xml  { head :ok }
    end
  end
end

ruby/rails/p2plearning/app/controllers/info_controller.rb
class InfoController < ApplicationController
  def intro
  end

  def terms
  end

  def privacy
  end

  def about
  end

end

ruby/rails/p2plearning/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!

  # GET /profiles/me/
  # GET /profiles/me.xml
  def me
    begin
      @profile = Profile.find(current_user)
    rescue ActiveRecord::RecordNotFound
      # create one for user
      Profile.create(:user => current_user, 
                                :desc => "no desc")
      @profile = Profile.find(current_user)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # GET /profiles/
  # GET /profiles.xml
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.xml
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.xml
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.xml
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to(@profile, :notice => 'Profile was successfully created.') }
        format.xml  { render :xml => @profile, :status => :created, :location => @profile }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.xml
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to(@profile, :notice => 'Profile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.xml
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to(profiles_url) }
      format.xml  { head :ok }
    end
  end
end

ruby/rails/p2plearning/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/rails/p2plearning/app/helpers/courses_helper.rb
module CoursesHelper
end

ruby/rails/p2plearning/app/helpers/info_helper.rb
module InfoHelper
end

ruby/rails/p2plearning/app/helpers/profiles_helper.rb
module ProfilesHelper
end

ruby/rails/p2plearning/app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/rails/p2plearning/app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

ruby/rails/p2plearning/app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Desc</th>
    <th>Created</th>
    <th>Updated</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.name %></td>
    <td><%= course.desc %></td>
    <td><%= course.created_at %></td>
    <td><%= course.updated_at %></td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

ruby/rails/p2plearning/app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

ruby/rails/p2plearning/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @course.name %>
</p>

<p>
  <b>Desc:</b>
  <p>
    <%= @course.desc %>
  </p>
</p>

<p>
  <b>Created:</b>
  <%= @course.created_at %>
  <br/>
  <b>Updated:</b>
  <%= @course.updated_at %>
</p>


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

ruby/rails/p2plearning/app/views/info/about.html.erb
<h1>about p2plearning team</h1>

<p>author: linjunhalida</p>

ruby/rails/p2plearning/app/views/info/intro.html.erb
<h1>what is p2plearning?</h1>
<p>this is a project on helping people learn from others, or learn something by themselves --- socially!</p>

ruby/rails/p2plearning/app/views/info/privacy.html.erb
<h1>Info#privacy</h1>
<p>Find me in app/views/info/privacy.html.erb</p>

ruby/rails/p2plearning/app/views/info/terms.html.erb
<h1>Info#terms</h1>
<p>Find me in app/views/info/terms.html.erb</p>